name: 'Docker:Dind Jest evaluator'
description: 'Docker:Dind Jest evaluator action for Tryber projects'
inputs:
  pr_author_username:
    description: 'Pull Request author username'
    required: true
outputs:
  result:
    description: 'Jest unit tests JSON results in base64 format.'
    value: ${{ steps.run-entrypoint.outputs.result }}
runs:
  using: 'composite'
  steps:
    - name: Export PR Author Username
      run: export INPUT_PR_AUTHOR_USERNAME=${{ inputs.pr_author_username }}
    - name: Run EntryPoint
      id: run-entrypoint
      run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
