name: 'Docker:Dind Jest evaluator'
description: 'Docker:Dind Jest evaluator action for Tryber projects'
inputs:
  challenges_folder:
    description: 'Folder that contains the docker-compose.yml file'
    default: 'app'
  wait-for:
    description: 'Url that npm start command waits for'
    default: ''
  pr_author_username:
    description: 'Pull Request author username'
    required: true
outputs:
  result:
    description: 'Jest unit tests JSON results in base64 format.'
    value: ${{ steps.run-entrypoint.outputs.result }}
runs:
  using: 'composite'
  steps:
    - name: Run EntryPoint
      id: run-entrypoint
      run:  export INPUT_CHALLENGES_FOLDER=${{ inputs.challenges_folder }} && \
            export INPUT_WAIT_FOR=${{ inputs.wait-for }} && \
            export INPUT_PR_AUTHOR_USERNAME=${{ inputs.pr_author_username }} && \
            ${{ github.action_path }}/entrypoint.sh
      shell: bash