name: 'Docker:Dind Jest evaluator'
description: 'Docker:Dind Jest evaluator action for Tryber projects'
inputs:
  challenges_folder:
    description: '(path) Folder that contains the docker-compose.yml file'
    default: 'app'
    required: true
  puppeteer_test:
    description: '(true | undefined) Install chrome´s puppeteer requirements'
    default: ''
  run_compose:
    description: '(true | undefined) Run docker-compose in `challenges_folder` after `npm install`'
    default: ''
  wait_for:
    description: '(url | undefined) Url that npm start command waits for'
    default: ''
  pr_author_username:
    description: '(string) Pull Request author username'
    required: true
outputs:
  result:
    description: 'Jest unit tests JSON results in base64 format.'
    value: ${{ steps.run-entrypoint.outputs.result }}
runs:
  using: 'composite'
  steps:
    - name: Run EntryPoint
      id: run-entrypoint
      run:  export INPUT_CHALLENGES_FOLDER=${{ inputs.challenges_folder }} && \
            export INPUT_PUPPETEER_TEST=${{ inputs.puppeteer_test }} && \
            export INPUT_RUN_COMPOSE=${{ inputs.run_compose }} && \
            export INPUT_WAIT_FOR=${{ inputs.wait_for }} && \
            export INPUT_PR_AUTHOR_USERNAME=${{ inputs.pr_author_username }} && \
            ${{ github.action_path }}/entrypoint.sh
      shell: bash