name: 'Docker:Dind Jest evaluator'
description: 'Docker:Dind Jest evaluator action for Tryber projects'
inputs:
  challenges_folder:
    description: 'Folder that contains the docker-compose.yml file'
    default: 'app'
  wait-for:
    description: 'Url that npm start command waits for'
    default: 'http://localhost:3000'
  pr_author_username:
    description: 'Pull Request author username'
    required: true

outputs:
  result:
    description: 'Jest unit tests JSON results in base64 format.'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.challenges_folder }}
    - ${{ inputs.wait-for }}